"""
blockchain_utils.py
===================
Shared Web3 helper layer for the PropChain blockchain integration.
Placed in web_app/ alongside server.py.

Loads abi.json and contract_address.txt from the same directory.
Run deploy.py once to generate those files before starting server.py.
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import time
from dataclasses import dataclass
from functools import wraps
from pathlib import Path
from typing import Optional

import requests
from web3 import Web3
from web3.exceptions import ContractLogicError

log = logging.getLogger("blockchain_utils")

# Files generated by deploy.py — live next to server.py
_HERE        = Path(__file__).resolve().parent
ABI_FILE     = _HERE / "abi.json"
ADDR_FILE    = _HERE / "contract_address.txt"
GENESIS      = 9999   # sentinel: no previous version


# ── Retry decorator ───────────────────────────────────────────────────────────

def _retry(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        for attempt in range(1, 4):
            try:
                return fn(*args, **kwargs)
            except (ContractLogicError, ValueError):
                raise
            except Exception as e:
                if attempt == 3:
                    raise
                log.warning(f"Attempt {attempt} failed ({e}), retrying…")
                time.sleep(2)
    return wrapper


# ── Data containers ───────────────────────────────────────────────────────────

@dataclass
class PredictionRecord:
    index:                int
    input_hash:           str
    output_hash:          str
    result_cid:           str
    model_version_index:  int
    dataset_index:        int
    requested_by:         str
    timestamp:            int
    verified:             bool


# ── Client ────────────────────────────────────────────────────────────────────

class BlockchainClient:
    """
    Minimal Web3 client for DataProvenancePro.

    Parameters
    ----------
    rpc_url     : HTTP RPC endpoint (default: Ganache)
    account     : Sender wallet address (default: accounts[0])
    private_key : Required for Sepolia; omit for Ganache
    pinata_jwt  : Pinata JWT for IPFS pinning (optional)
    """

    def __init__(
        self,
        rpc_url:     str           = "http://127.0.0.1:7545",
        account:     Optional[str] = None,
        private_key: Optional[str] = None,
        pinata_jwt:  Optional[str] = None,
    ):
        self.private_key = private_key
        self.pinata_jwt  = pinata_jwt

        self.w3 = Web3(Web3.HTTPProvider(rpc_url, request_kwargs={"timeout": 30}))
        if not self.w3.is_connected():
            raise ConnectionError(f"Cannot connect to blockchain node at {rpc_url}")

        if account:
            self.account = Web3.to_checksum_address(account)
        elif private_key:
            self.account = self.w3.eth.account.from_key(private_key).address
        else:
            self.account = self.w3.eth.accounts[0]

        if not ABI_FILE.exists():
            raise FileNotFoundError(
                f"abi.json not found at {ABI_FILE}\n"
                "Run  python deploy.py  from the web_app/ folder first."
            )
        if not ADDR_FILE.exists():
            raise FileNotFoundError(
                f"contract_address.txt not found at {ADDR_FILE}\n"
                "Run  python deploy.py  from the web_app/ folder first."
            )

        abi     = json.loads(ABI_FILE.read_text())
        address = ADDR_FILE.read_text().strip()
        self.contract = self.w3.eth.contract(
            address=Web3.to_checksum_address(address), abi=abi
        )
        log.info(f"Blockchain connected  chain={self.w3.eth.chain_id}  "
                 f"account={self.account}  contract={self.contract.address}")

    # ── Internal ──────────────────────────────────────────────────────────────

    @_retry
    def _send(self, fn, gas: int = 500_000) -> str:
        if self.private_key:
            nonce   = self.w3.eth.get_transaction_count(self.account, "pending")
            tx      = fn.build_transaction({
                "from": self.account, "nonce": nonce,
                "gasPrice": self.w3.eth.gas_price, "gas": gas,
            })
            signed  = self.w3.eth.account.sign_transaction(tx, self.private_key)
            tx_hash = self.w3.eth.send_raw_transaction(signed.raw_transaction)
        else:
            tx_hash = fn.transact({"from": self.account, "gas": gas})

        receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash, timeout=120)
        if receipt.status != 1:
            raise RuntimeError(f"Transaction reverted: {tx_hash.hex()}")
        log.info(f"Tx confirmed  {tx_hash.hex()[:20]}…  gas={receipt.gasUsed:,}")
        return tx_hash.hex()

    # ── Hashing ──────────────────────────────────────────────────────────────

    @staticmethod
    def hash_bytes(data: bytes) -> str:
        return hashlib.sha256(data).hexdigest()

    @staticmethod
    def hash_json(obj) -> str:
        s = json.dumps(obj, sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(s.encode()).hexdigest()

    # ── IPFS ─────────────────────────────────────────────────────────────────

    def pin_json_to_ipfs(self, obj, name: str = "record") -> str:
        if not self.pinata_jwt:
            return "NO_IPFS_CONFIGURED"
        payload  = json.dumps(obj, sort_keys=True).encode()
        url      = "https://api.pinata.cloud/pinning/pinFileToIPFS"
        headers  = {"Authorization": f"Bearer {self.pinata_jwt}"}
        files    = {"file": (f"{name}.json", payload, "application/json")}
        resp     = requests.post(url, headers=headers, files=files, timeout=30)
        resp.raise_for_status()
        cid = resp.json()["IpfsHash"]
        log.info(f"Pinned to IPFS: {cid}")
        return cid

    # ── Prediction ────────────────────────────────────────────────────────────

    def store_prediction(
        self,
        input_hash:          str,
        output_hash:         str,
        result_cid:          str,
        model_version_index: int,
        dataset_index:       int,
    ) -> dict:
        fn    = self.contract.functions.storePrediction(
            input_hash, output_hash, result_cid,
            model_version_index, dataset_index,
        )
        tx    = self._send(fn)
        index = self.contract.functions.getPredictionCount().call() - 1
        log.info(f"Prediction stored  index={index}")
        return {"tx": tx, "index": index}

    def get_prediction(self, index: int) -> PredictionRecord:
        p = self.contract.functions.getPrediction(index).call()
        return PredictionRecord(index, *p)

    def get_all_predictions(self) -> list[PredictionRecord]:
        n = self.contract.functions.getPredictionCount().call()
        return [self.get_prediction(i) for i in range(n)]

    def verify_prediction(self, index: int) -> str:
        return self._send(self.contract.functions.verifyPrediction(index))

    # ── Dataset ───────────────────────────────────────────────────────────────

    def store_dataset(self, data_hash: str, ipfs_cid: str,
                      prev: int, label: str) -> dict:
        fn    = self.contract.functions.storeDataset(data_hash, ipfs_cid, prev, label)
        tx    = self._send(fn)
        index = self.contract.functions.getDatasetCount().call() - 1
        return {"tx": tx, "index": index}

    # ── Model version ─────────────────────────────────────────────────────────

    def store_model_version(self, model_hash: str, ipfs_cid: str,
                            algorithm_tag: str, trained_on_dataset: int) -> dict:
        fn    = self.contract.functions.storeModelVersion(
            model_hash, ipfs_cid, algorithm_tag, trained_on_dataset
        )
        tx    = self._send(fn)
        index = self.contract.functions.getModelVersionCount().call() - 1
        return {"tx": tx, "index": index}

    # ── Roles ─────────────────────────────────────────────────────────────────

    def grant_researcher(self, address: str) -> str:
        return self._send(self.contract.functions.grantResearcher(
            Web3.to_checksum_address(address)))

    def grant_ml_system(self, address: str) -> str:
        return self._send(self.contract.functions.grantMLSystem(
            Web3.to_checksum_address(address)))

    # ── Summary ───────────────────────────────────────────────────────────────

    def summary(self) -> dict:
        return {
            "datasets":       self.contract.functions.getDatasetCount().call(),
            "model_versions": self.contract.functions.getModelVersionCount().call(),
            "predictions":    self.contract.functions.getPredictionCount().call(),
            "account":        self.account,
            "contract":       self.contract.address,
            "chain_id":       self.w3.eth.chain_id,
        }
